-- ============================================================
--  进销存系统 —— D1 种子数据（由 cf/gen_seed.py 生成，勿手改）
--
--  内容：角色 / 权限点 / 角色权限关联 / admin 账号 / 默认仓库
--  默认账号：admin / admin123   ← 首次登录后请立即修改
--
--  执行：wrangler d1 execute inventory --file=cf/seed.sql --remote
-- ============================================================

-- 幂等：先清空再插入（只动权限相关表和 admin，不碰业务数据）
DELETE FROM role_permissions;
DELETE FROM permissions;
DELETE FROM roles;

-- ---------- 角色 ----------
INSERT INTO roles (id, name, description, created_at) VALUES (1, 'admin', '全部权限，含用户/角色/系统维护', '2026-09-29 16:57:37.991078');
INSERT INTO roles (id, name, description, created_at) VALUES (2, 'manager', '业务全流程 + 审核，无系统管理', '2026-09-29 16:57:38.057471');
INSERT INTO roles (id, name, description, created_at) VALUES (3, 'sales', '客户与销售业务，可建单不可审核', '2026-09-29 16:57:38.063474');
INSERT INTO roles (id, name, description, created_at) VALUES (4, 'purchaser', '供应商与采购业务，可建单不可审核', '2026-09-29 16:57:38.067482');
INSERT INTO roles (id, name, description, created_at) VALUES (5, 'warehouse', '库存、调拨、盘点、出入库；负责采购入库与销售出库', '2026-09-29 16:57:38.070480');
INSERT INTO roles (id, name, description, created_at) VALUES (6, 'finance', '收付款与报表，单据只读', '2026-09-29 16:57:38.073482');
INSERT INTO roles (id, name, description, created_at) VALUES (7, 'viewer', '仅可查看，不能做任何修改', '2026-09-29 16:57:38.076485');

-- ---------- 权限点 ----------
INSERT INTO permissions (id, code, name, module, created_at) VALUES (1, 'dashboard:view', '查看首页', 'dashboard', '2026-09-29 16:57:37.957033');
INSERT INTO permissions (id, code, name, module, created_at) VALUES (2, 'supplier:view', '查看供应商', 'supplier', '2026-09-29 16:57:37.957033');
INSERT INTO permissions (id, code, name, module, created_at) VALUES (3, 'supplier:add', '新增供应商', 'supplier', '2026-09-29 16:57:37.957540');
INSERT INTO permissions (id, code, name, module, created_at) VALUES (4, 'supplier:edit', '编辑供应商', 'supplier', '2026-09-29 16:57:37.957540');
INSERT INTO permissions (id, code, name, module, created_at) VALUES (5, 'supplier:delete', '删除供应商', 'supplier', '2026-09-29 16:57:37.957540');
INSERT INTO permissions (id, code, name, module, created_at) VALUES (6, 'customer:view', '查看客户', 'customer', '2026-09-29 16:57:37.957540');
INSERT INTO permissions (id, code, name, module, created_at) VALUES (7, 'customer:add', '新增客户', 'customer', '2026-09-29 16:57:37.957540');
INSERT INTO permissions (id, code, name, module, created_at) VALUES (8, 'customer:edit', '编辑客户', 'customer', '2026-09-29 16:57:37.957540');
INSERT INTO permissions (id, code, name, module, created_at) VALUES (9, 'customer:delete', '删除客户', 'customer', '2026-09-29 16:57:37.957540');
INSERT INTO permissions (id, code, name, module, created_at) VALUES (10, 'product:view', '查看商品', 'product', '2026-09-29 16:57:37.957540');
INSERT INTO permissions (id, code, name, module, created_at) VALUES (11, 'product:add', '新增商品', 'product', '2026-09-29 16:57:37.957540');
INSERT INTO permissions (id, code, name, module, created_at) VALUES (12, 'product:edit', '编辑商品', 'product', '2026-09-29 16:57:37.957540');
INSERT INTO permissions (id, code, name, module, created_at) VALUES (13, 'product:delete', '删除商品', 'product', '2026-09-29 16:57:37.957540');
INSERT INTO permissions (id, code, name, module, created_at) VALUES (14, 'product:export', '导出商品', 'product', '2026-09-29 16:57:37.957540');
INSERT INTO permissions (id, code, name, module, created_at) VALUES (15, 'category:view', '查看分类', 'category', '2026-09-29 16:57:37.957540');
INSERT INTO permissions (id, code, name, module, created_at) VALUES (16, 'category:add', '新增分类', 'category', '2026-09-29 16:57:37.957540');
INSERT INTO permissions (id, code, name, module, created_at) VALUES (17, 'category:edit', '编辑分类', 'category', '2026-09-29 16:57:37.957540');
INSERT INTO permissions (id, code, name, module, created_at) VALUES (18, 'category:delete', '删除分类', 'category', '2026-09-29 16:57:37.957540');
INSERT INTO permissions (id, code, name, module, created_at) VALUES (19, 'purchase:view', '查看采购单', 'purchase', '2026-09-29 16:57:37.957540');
INSERT INTO permissions (id, code, name, module, created_at) VALUES (20, 'purchase:add', '新增采购单', 'purchase', '2026-09-29 16:57:37.957540');
INSERT INTO permissions (id, code, name, module, created_at) VALUES (21, 'purchase:edit', '编辑采购单', 'purchase', '2026-09-29 16:57:37.957540');
INSERT INTO permissions (id, code, name, module, created_at) VALUES (22, 'purchase:delete', '删除采购单', 'purchase', '2026-09-29 16:57:37.957540');
INSERT INTO permissions (id, code, name, module, created_at) VALUES (23, 'purchase:approve', '审核采购单', 'purchase', '2026-09-29 16:57:37.957540');
INSERT INTO permissions (id, code, name, module, created_at) VALUES (24, 'purchase:receive', '采购入库', 'purchase', '2026-09-29 16:57:37.957540');
INSERT INTO permissions (id, code, name, module, created_at) VALUES (25, 'purchase:cancel', '作废采购单', 'purchase', '2026-09-29 16:57:37.957540');
INSERT INTO permissions (id, code, name, module, created_at) VALUES (26, 'purchase:print', '打印采购单', 'purchase', '2026-09-29 16:57:37.957540');
INSERT INTO permissions (id, code, name, module, created_at) VALUES (27, 'purchase:export', '导出采购单', 'purchase', '2026-09-29 16:57:37.957540');
INSERT INTO permissions (id, code, name, module, created_at) VALUES (28, 'purchase_return:view', '查看采购退货', 'purchase_return', '2026-09-29 16:57:37.957540');
INSERT INTO permissions (id, code, name, module, created_at) VALUES (29, 'purchase_return:add', '新增采购退货', 'purchase_return', '2026-09-29 16:57:37.957540');
INSERT INTO permissions (id, code, name, module, created_at) VALUES (30, 'purchase_return:approve', '审核采购退货', 'purchase_return', '2026-09-29 16:57:37.957540');
INSERT INTO permissions (id, code, name, module, created_at) VALUES (31, 'purchase_return:ship', '采购退货出库', 'purchase_return', '2026-09-29 16:57:37.957540');
INSERT INTO permissions (id, code, name, module, created_at) VALUES (32, 'purchase_return:cancel', '作废采购退货', 'purchase_return', '2026-09-29 16:57:37.957540');
INSERT INTO permissions (id, code, name, module, created_at) VALUES (33, 'sales:view', '查看销售单', 'sales', '2026-09-29 16:57:37.957540');
INSERT INTO permissions (id, code, name, module, created_at) VALUES (34, 'sales:add', '新增销售单', 'sales', '2026-09-29 16:57:37.957540');
INSERT INTO permissions (id, code, name, module, created_at) VALUES (35, 'sales:edit', '编辑销售单', 'sales', '2026-09-29 16:57:37.957540');
INSERT INTO permissions (id, code, name, module, created_at) VALUES (36, 'sales:delete', '删除销售单', 'sales', '2026-09-29 16:57:37.957540');
INSERT INTO permissions (id, code, name, module, created_at) VALUES (37, 'sales:approve', '审核销售单', 'sales', '2026-09-29 16:57:37.957540');
INSERT INTO permissions (id, code, name, module, created_at) VALUES (38, 'sales:ship', '销售出库', 'sales', '2026-09-29 16:57:37.957540');
INSERT INTO permissions (id, code, name, module, created_at) VALUES (39, 'sales:cancel', '作废销售单', 'sales', '2026-09-29 16:57:37.957540');
INSERT INTO permissions (id, code, name, module, created_at) VALUES (40, 'sales:print', '打印销售单', 'sales', '2026-09-29 16:57:37.957540');
INSERT INTO permissions (id, code, name, module, created_at) VALUES (41, 'sales:export', '导出销售单', 'sales', '2026-09-29 16:57:37.957540');
INSERT INTO permissions (id, code, name, module, created_at) VALUES (42, 'sale_return:view', '查看销售退货', 'sale_return', '2026-09-29 16:57:37.957540');
INSERT INTO permissions (id, code, name, module, created_at) VALUES (43, 'sale_return:add', '新增销售退货', 'sale_return', '2026-09-29 16:57:37.957540');
INSERT INTO permissions (id, code, name, module, created_at) VALUES (44, 'sale_return:approve', '审核销售退货', 'sale_return', '2026-09-29 16:57:37.957540');
INSERT INTO permissions (id, code, name, module, created_at) VALUES (45, 'sale_return:receive', '销售退货入库', 'sale_return', '2026-09-29 16:57:37.957540');
INSERT INTO permissions (id, code, name, module, created_at) VALUES (46, 'sale_return:cancel', '作废销售退货', 'sale_return', '2026-09-29 16:57:37.957540');
INSERT INTO permissions (id, code, name, module, created_at) VALUES (47, 'inventory:view', '查看库存', 'inventory', '2026-09-29 16:57:37.957540');
INSERT INTO permissions (id, code, name, module, created_at) VALUES (48, 'inventory:export', '导出库存', 'inventory', '2026-09-29 16:57:37.957540');
INSERT INTO permissions (id, code, name, module, created_at) VALUES (49, 'warehouse:view', '查看仓库', 'warehouse', '2026-09-29 16:57:37.957540');
INSERT INTO permissions (id, code, name, module, created_at) VALUES (50, 'warehouse:add', '新增仓库', 'warehouse', '2026-09-29 16:57:37.957540');
INSERT INTO permissions (id, code, name, module, created_at) VALUES (51, 'warehouse:edit', '编辑仓库', 'warehouse', '2026-09-29 16:57:37.957540');
INSERT INTO permissions (id, code, name, module, created_at) VALUES (52, 'warehouse:delete', '删除仓库', 'warehouse', '2026-09-29 16:57:37.957540');
INSERT INTO permissions (id, code, name, module, created_at) VALUES (53, 'transfer:view', '查看调拨单', 'transfer', '2026-09-29 16:57:37.957540');
INSERT INTO permissions (id, code, name, module, created_at) VALUES (54, 'transfer:add', '新增调拨单', 'transfer', '2026-09-29 16:57:37.957540');
INSERT INTO permissions (id, code, name, module, created_at) VALUES (55, 'transfer:approve', '执行调拨', 'transfer', '2026-09-29 16:57:37.957540');
INSERT INTO permissions (id, code, name, module, created_at) VALUES (56, 'transfer:cancel', '作废调拨单', 'transfer', '2026-09-29 16:57:37.957540');
INSERT INTO permissions (id, code, name, module, created_at) VALUES (57, 'stockcheck:view', '查看盘点单', 'stockcheck', '2026-09-29 16:57:37.957540');
INSERT INTO permissions (id, code, name, module, created_at) VALUES (58, 'stockcheck:add', '新建盘点单', 'stockcheck', '2026-09-29 16:57:37.957540');
INSERT INTO permissions (id, code, name, module, created_at) VALUES (59, 'stockcheck:approve', '审核调账', 'stockcheck', '2026-09-29 16:57:37.957540');
INSERT INTO permissions (id, code, name, module, created_at) VALUES (60, 'stockcheck:cancel', '作废盘点单', 'stockcheck', '2026-09-29 16:57:37.957540');
INSERT INTO permissions (id, code, name, module, created_at) VALUES (61, 'stocklog:view', '查看出入库明细', 'stocklog', '2026-09-29 16:57:37.957540');
INSERT INTO permissions (id, code, name, module, created_at) VALUES (62, 'stocklog:export', '导出出入库明细', 'stocklog', '2026-09-29 16:57:37.957540');
INSERT INTO permissions (id, code, name, module, created_at) VALUES (63, 'stocklog:init', '生成期初流水', 'stocklog', '2026-09-29 16:57:37.957540');
INSERT INTO permissions (id, code, name, module, created_at) VALUES (64, 'finance:view', '查看收付款', 'finance', '2026-09-29 16:57:37.957540');
INSERT INTO permissions (id, code, name, module, created_at) VALUES (65, 'finance:add', '新增收付款', 'finance', '2026-09-29 16:57:37.957540');
INSERT INTO permissions (id, code, name, module, created_at) VALUES (66, 'finance:edit', '编辑收付款', 'finance', '2026-09-29 16:57:37.957540');
INSERT INTO permissions (id, code, name, module, created_at) VALUES (67, 'finance:delete', '删除收付款', 'finance', '2026-09-29 16:57:37.957540');
INSERT INTO permissions (id, code, name, module, created_at) VALUES (68, 'finance:export', '导出收付款', 'finance', '2026-09-29 16:57:37.957540');
INSERT INTO permissions (id, code, name, module, created_at) VALUES (69, 'report:view', '查看报表', 'report', '2026-09-29 16:57:37.957540');
INSERT INTO permissions (id, code, name, module, created_at) VALUES (70, 'report:export', '导出报表', 'report', '2026-09-29 16:57:37.957540');
INSERT INTO permissions (id, code, name, module, created_at) VALUES (71, 'user:view', '查看用户', 'user', '2026-09-29 16:57:37.957540');
INSERT INTO permissions (id, code, name, module, created_at) VALUES (72, 'user:add', '新增用户', 'user', '2026-09-29 16:57:37.957540');
INSERT INTO permissions (id, code, name, module, created_at) VALUES (73, 'user:edit', '编辑用户', 'user', '2026-09-29 16:57:37.957540');
INSERT INTO permissions (id, code, name, module, created_at) VALUES (74, 'user:delete', '删除用户', 'user', '2026-09-29 16:57:37.957540');
INSERT INTO permissions (id, code, name, module, created_at) VALUES (75, 'user:resetpwd', '重置密码', 'user', '2026-09-29 16:57:37.957540');
INSERT INTO permissions (id, code, name, module, created_at) VALUES (76, 'role:view', '查看角色', 'role', '2026-09-29 16:57:37.957540');
INSERT INTO permissions (id, code, name, module, created_at) VALUES (77, 'role:add', '新增角色', 'role', '2026-09-29 16:57:37.957540');
INSERT INTO permissions (id, code, name, module, created_at) VALUES (78, 'role:edit', '编辑角色', 'role', '2026-09-29 16:57:37.957540');
INSERT INTO permissions (id, code, name, module, created_at) VALUES (79, 'role:delete', '删除角色', 'role', '2026-09-29 16:57:37.957540');
INSERT INTO permissions (id, code, name, module, created_at) VALUES (80, 'log:view', '查看操作日志', 'log', '2026-09-29 16:57:37.957540');
INSERT INTO permissions (id, code, name, module, created_at) VALUES (81, 'log:export', '导出操作日志', 'log', '2026-09-29 16:57:37.957540');
INSERT INTO permissions (id, code, name, module, created_at) VALUES (82, 'system:check', '数据自检', 'system', '2026-09-29 16:57:37.957540');
INSERT INTO permissions (id, code, name, module, created_at) VALUES (83, 'system:fix', '自动修复', 'system', '2026-09-29 16:57:37.957540');
INSERT INTO permissions (id, code, name, module, created_at) VALUES (84, 'system:print', '打印模板设置', 'system', '2026-09-29 16:57:37.957540');

-- ---------- 角色-权限关联 ----------
INSERT INTO role_permissions (role_id, permission_id) VALUES (1, 1);
INSERT INTO role_permissions (role_id, permission_id) VALUES (1, 2);
INSERT INTO role_permissions (role_id, permission_id) VALUES (1, 3);
INSERT INTO role_permissions (role_id, permission_id) VALUES (1, 4);
INSERT INTO role_permissions (role_id, permission_id) VALUES (1, 5);
INSERT INTO role_permissions (role_id, permission_id) VALUES (1, 6);
INSERT INTO role_permissions (role_id, permission_id) VALUES (1, 7);
INSERT INTO role_permissions (role_id, permission_id) VALUES (1, 8);
INSERT INTO role_permissions (role_id, permission_id) VALUES (1, 9);
INSERT INTO role_permissions (role_id, permission_id) VALUES (1, 10);
INSERT INTO role_permissions (role_id, permission_id) VALUES (1, 11);
INSERT INTO role_permissions (role_id, permission_id) VALUES (1, 12);
INSERT INTO role_permissions (role_id, permission_id) VALUES (1, 13);
INSERT INTO role_permissions (role_id, permission_id) VALUES (1, 14);
INSERT INTO role_permissions (role_id, permission_id) VALUES (1, 15);
INSERT INTO role_permissions (role_id, permission_id) VALUES (1, 16);
INSERT INTO role_permissions (role_id, permission_id) VALUES (1, 17);
INSERT INTO role_permissions (role_id, permission_id) VALUES (1, 18);
INSERT INTO role_permissions (role_id, permission_id) VALUES (1, 19);
INSERT INTO role_permissions (role_id, permission_id) VALUES (1, 20);
INSERT INTO role_permissions (role_id, permission_id) VALUES (1, 21);
INSERT INTO role_permissions (role_id, permission_id) VALUES (1, 22);
INSERT INTO role_permissions (role_id, permission_id) VALUES (1, 23);
INSERT INTO role_permissions (role_id, permission_id) VALUES (1, 24);
INSERT INTO role_permissions (role_id, permission_id) VALUES (1, 25);
INSERT INTO role_permissions (role_id, permission_id) VALUES (1, 26);
INSERT INTO role_permissions (role_id, permission_id) VALUES (1, 27);
INSERT INTO role_permissions (role_id, permission_id) VALUES (1, 28);
INSERT INTO role_permissions (role_id, permission_id) VALUES (1, 29);
INSERT INTO role_permissions (role_id, permission_id) VALUES (1, 30);
INSERT INTO role_permissions (role_id, permission_id) VALUES (1, 31);
INSERT INTO role_permissions (role_id, permission_id) VALUES (1, 32);
INSERT INTO role_permissions (role_id, permission_id) VALUES (1, 33);
INSERT INTO role_permissions (role_id, permission_id) VALUES (1, 34);
INSERT INTO role_permissions (role_id, permission_id) VALUES (1, 35);
INSERT INTO role_permissions (role_id, permission_id) VALUES (1, 36);
INSERT INTO role_permissions (role_id, permission_id) VALUES (1, 37);
INSERT INTO role_permissions (role_id, permission_id) VALUES (1, 38);
INSERT INTO role_permissions (role_id, permission_id) VALUES (1, 39);
INSERT INTO role_permissions (role_id, permission_id) VALUES (1, 40);
INSERT INTO role_permissions (role_id, permission_id) VALUES (1, 41);
INSERT INTO role_permissions (role_id, permission_id) VALUES (1, 42);
INSERT INTO role_permissions (role_id, permission_id) VALUES (1, 43);
INSERT INTO role_permissions (role_id, permission_id) VALUES (1, 44);
INSERT INTO role_permissions (role_id, permission_id) VALUES (1, 45);
INSERT INTO role_permissions (role_id, permission_id) VALUES (1, 46);
INSERT INTO role_permissions (role_id, permission_id) VALUES (1, 47);
INSERT INTO role_permissions (role_id, permission_id) VALUES (1, 48);
INSERT INTO role_permissions (role_id, permission_id) VALUES (1, 49);
INSERT INTO role_permissions (role_id, permission_id) VALUES (1, 50);
INSERT INTO role_permissions (role_id, permission_id) VALUES (1, 51);
INSERT INTO role_permissions (role_id, permission_id) VALUES (1, 52);
INSERT INTO role_permissions (role_id, permission_id) VALUES (1, 53);
INSERT INTO role_permissions (role_id, permission_id) VALUES (1, 54);
INSERT INTO role_permissions (role_id, permission_id) VALUES (1, 55);
INSERT INTO role_permissions (role_id, permission_id) VALUES (1, 56);
INSERT INTO role_permissions (role_id, permission_id) VALUES (1, 57);
INSERT INTO role_permissions (role_id, permission_id) VALUES (1, 58);
INSERT INTO role_permissions (role_id, permission_id) VALUES (1, 59);
INSERT INTO role_permissions (role_id, permission_id) VALUES (1, 60);
INSERT INTO role_permissions (role_id, permission_id) VALUES (1, 61);
INSERT INTO role_permissions (role_id, permission_id) VALUES (1, 62);
INSERT INTO role_permissions (role_id, permission_id) VALUES (1, 63);
INSERT INTO role_permissions (role_id, permission_id) VALUES (1, 64);
INSERT INTO role_permissions (role_id, permission_id) VALUES (1, 65);
INSERT INTO role_permissions (role_id, permission_id) VALUES (1, 66);
INSERT INTO role_permissions (role_id, permission_id) VALUES (1, 67);
INSERT INTO role_permissions (role_id, permission_id) VALUES (1, 68);
INSERT INTO role_permissions (role_id, permission_id) VALUES (1, 69);
INSERT INTO role_permissions (role_id, permission_id) VALUES (1, 70);
INSERT INTO role_permissions (role_id, permission_id) VALUES (1, 71);
INSERT INTO role_permissions (role_id, permission_id) VALUES (1, 72);
INSERT INTO role_permissions (role_id, permission_id) VALUES (1, 73);
INSERT INTO role_permissions (role_id, permission_id) VALUES (1, 74);
INSERT INTO role_permissions (role_id, permission_id) VALUES (1, 75);
INSERT INTO role_permissions (role_id, permission_id) VALUES (1, 76);
INSERT INTO role_permissions (role_id, permission_id) VALUES (1, 77);
INSERT INTO role_permissions (role_id, permission_id) VALUES (1, 78);
INSERT INTO role_permissions (role_id, permission_id) VALUES (1, 79);
INSERT INTO role_permissions (role_id, permission_id) VALUES (1, 80);
INSERT INTO role_permissions (role_id, permission_id) VALUES (1, 81);
INSERT INTO role_permissions (role_id, permission_id) VALUES (1, 82);
INSERT INTO role_permissions (role_id, permission_id) VALUES (1, 83);
INSERT INTO role_permissions (role_id, permission_id) VALUES (1, 84);
INSERT INTO role_permissions (role_id, permission_id) VALUES (2, 1);
INSERT INTO role_permissions (role_id, permission_id) VALUES (2, 2);
INSERT INTO role_permissions (role_id, permission_id) VALUES (2, 3);
INSERT INTO role_permissions (role_id, permission_id) VALUES (2, 4);
INSERT INTO role_permissions (role_id, permission_id) VALUES (2, 5);
INSERT INTO role_permissions (role_id, permission_id) VALUES (2, 6);
INSERT INTO role_permissions (role_id, permission_id) VALUES (2, 7);
INSERT INTO role_permissions (role_id, permission_id) VALUES (2, 8);
INSERT INTO role_permissions (role_id, permission_id) VALUES (2, 9);
INSERT INTO role_permissions (role_id, permission_id) VALUES (2, 10);
INSERT INTO role_permissions (role_id, permission_id) VALUES (2, 11);
INSERT INTO role_permissions (role_id, permission_id) VALUES (2, 12);
INSERT INTO role_permissions (role_id, permission_id) VALUES (2, 13);
INSERT INTO role_permissions (role_id, permission_id) VALUES (2, 14);
INSERT INTO role_permissions (role_id, permission_id) VALUES (2, 15);
INSERT INTO role_permissions (role_id, permission_id) VALUES (2, 16);
INSERT INTO role_permissions (role_id, permission_id) VALUES (2, 17);
INSERT INTO role_permissions (role_id, permission_id) VALUES (2, 18);
INSERT INTO role_permissions (role_id, permission_id) VALUES (2, 19);
INSERT INTO role_permissions (role_id, permission_id) VALUES (2, 20);
INSERT INTO role_permissions (role_id, permission_id) VALUES (2, 21);
INSERT INTO role_permissions (role_id, permission_id) VALUES (2, 22);
INSERT INTO role_permissions (role_id, permission_id) VALUES (2, 23);
INSERT INTO role_permissions (role_id, permission_id) VALUES (2, 24);
INSERT INTO role_permissions (role_id, permission_id) VALUES (2, 25);
INSERT INTO role_permissions (role_id, permission_id) VALUES (2, 26);
INSERT INTO role_permissions (role_id, permission_id) VALUES (2, 27);
INSERT INTO role_permissions (role_id, permission_id) VALUES (2, 28);
INSERT INTO role_permissions (role_id, permission_id) VALUES (2, 29);
INSERT INTO role_permissions (role_id, permission_id) VALUES (2, 30);
INSERT INTO role_permissions (role_id, permission_id) VALUES (2, 31);
INSERT INTO role_permissions (role_id, permission_id) VALUES (2, 32);
INSERT INTO role_permissions (role_id, permission_id) VALUES (2, 33);
INSERT INTO role_permissions (role_id, permission_id) VALUES (2, 34);
INSERT INTO role_permissions (role_id, permission_id) VALUES (2, 35);
INSERT INTO role_permissions (role_id, permission_id) VALUES (2, 36);
INSERT INTO role_permissions (role_id, permission_id) VALUES (2, 37);
INSERT INTO role_permissions (role_id, permission_id) VALUES (2, 38);
INSERT INTO role_permissions (role_id, permission_id) VALUES (2, 39);
INSERT INTO role_permissions (role_id, permission_id) VALUES (2, 40);
INSERT INTO role_permissions (role_id, permission_id) VALUES (2, 41);
INSERT INTO role_permissions (role_id, permission_id) VALUES (2, 42);
INSERT INTO role_permissions (role_id, permission_id) VALUES (2, 43);
INSERT INTO role_permissions (role_id, permission_id) VALUES (2, 44);
INSERT INTO role_permissions (role_id, permission_id) VALUES (2, 45);
INSERT INTO role_permissions (role_id, permission_id) VALUES (2, 46);
INSERT INTO role_permissions (role_id, permission_id) VALUES (2, 47);
INSERT INTO role_permissions (role_id, permission_id) VALUES (2, 48);
INSERT INTO role_permissions (role_id, permission_id) VALUES (2, 49);
INSERT INTO role_permissions (role_id, permission_id) VALUES (2, 50);
INSERT INTO role_permissions (role_id, permission_id) VALUES (2, 51);
INSERT INTO role_permissions (role_id, permission_id) VALUES (2, 52);
INSERT INTO role_permissions (role_id, permission_id) VALUES (2, 53);
INSERT INTO role_permissions (role_id, permission_id) VALUES (2, 54);
INSERT INTO role_permissions (role_id, permission_id) VALUES (2, 55);
INSERT INTO role_permissions (role_id, permission_id) VALUES (2, 56);
INSERT INTO role_permissions (role_id, permission_id) VALUES (2, 57);
INSERT INTO role_permissions (role_id, permission_id) VALUES (2, 58);
INSERT INTO role_permissions (role_id, permission_id) VALUES (2, 59);
INSERT INTO role_permissions (role_id, permission_id) VALUES (2, 60);
INSERT INTO role_permissions (role_id, permission_id) VALUES (2, 61);
INSERT INTO role_permissions (role_id, permission_id) VALUES (2, 62);
INSERT INTO role_permissions (role_id, permission_id) VALUES (2, 63);
INSERT INTO role_permissions (role_id, permission_id) VALUES (2, 64);
INSERT INTO role_permissions (role_id, permission_id) VALUES (2, 65);
INSERT INTO role_permissions (role_id, permission_id) VALUES (2, 66);
INSERT INTO role_permissions (role_id, permission_id) VALUES (2, 67);
INSERT INTO role_permissions (role_id, permission_id) VALUES (2, 68);
INSERT INTO role_permissions (role_id, permission_id) VALUES (2, 69);
INSERT INTO role_permissions (role_id, permission_id) VALUES (2, 70);
INSERT INTO role_permissions (role_id, permission_id) VALUES (3, 1);
INSERT INTO role_permissions (role_id, permission_id) VALUES (3, 6);
INSERT INTO role_permissions (role_id, permission_id) VALUES (3, 7);
INSERT INTO role_permissions (role_id, permission_id) VALUES (3, 8);
INSERT INTO role_permissions (role_id, permission_id) VALUES (3, 10);
INSERT INTO role_permissions (role_id, permission_id) VALUES (3, 15);
INSERT INTO role_permissions (role_id, permission_id) VALUES (3, 33);
INSERT INTO role_permissions (role_id, permission_id) VALUES (3, 34);
INSERT INTO role_permissions (role_id, permission_id) VALUES (3, 35);
INSERT INTO role_permissions (role_id, permission_id) VALUES (3, 40);
INSERT INTO role_permissions (role_id, permission_id) VALUES (3, 42);
INSERT INTO role_permissions (role_id, permission_id) VALUES (3, 43);
INSERT INTO role_permissions (role_id, permission_id) VALUES (3, 47);
INSERT INTO role_permissions (role_id, permission_id) VALUES (3, 69);
INSERT INTO role_permissions (role_id, permission_id) VALUES (4, 1);
INSERT INTO role_permissions (role_id, permission_id) VALUES (4, 2);
INSERT INTO role_permissions (role_id, permission_id) VALUES (4, 3);
INSERT INTO role_permissions (role_id, permission_id) VALUES (4, 4);
INSERT INTO role_permissions (role_id, permission_id) VALUES (4, 10);
INSERT INTO role_permissions (role_id, permission_id) VALUES (4, 15);
INSERT INTO role_permissions (role_id, permission_id) VALUES (4, 19);
INSERT INTO role_permissions (role_id, permission_id) VALUES (4, 20);
INSERT INTO role_permissions (role_id, permission_id) VALUES (4, 21);
INSERT INTO role_permissions (role_id, permission_id) VALUES (4, 26);
INSERT INTO role_permissions (role_id, permission_id) VALUES (4, 28);
INSERT INTO role_permissions (role_id, permission_id) VALUES (4, 29);
INSERT INTO role_permissions (role_id, permission_id) VALUES (4, 47);
INSERT INTO role_permissions (role_id, permission_id) VALUES (4, 69);
INSERT INTO role_permissions (role_id, permission_id) VALUES (5, 1);
INSERT INTO role_permissions (role_id, permission_id) VALUES (5, 10);
INSERT INTO role_permissions (role_id, permission_id) VALUES (5, 15);
INSERT INTO role_permissions (role_id, permission_id) VALUES (5, 19);
INSERT INTO role_permissions (role_id, permission_id) VALUES (5, 24);
INSERT INTO role_permissions (role_id, permission_id) VALUES (5, 28);
INSERT INTO role_permissions (role_id, permission_id) VALUES (5, 31);
INSERT INTO role_permissions (role_id, permission_id) VALUES (5, 33);
INSERT INTO role_permissions (role_id, permission_id) VALUES (5, 38);
INSERT INTO role_permissions (role_id, permission_id) VALUES (5, 42);
INSERT INTO role_permissions (role_id, permission_id) VALUES (5, 45);
INSERT INTO role_permissions (role_id, permission_id) VALUES (5, 47);
INSERT INTO role_permissions (role_id, permission_id) VALUES (5, 48);
INSERT INTO role_permissions (role_id, permission_id) VALUES (5, 49);
INSERT INTO role_permissions (role_id, permission_id) VALUES (5, 50);
INSERT INTO role_permissions (role_id, permission_id) VALUES (5, 51);
INSERT INTO role_permissions (role_id, permission_id) VALUES (5, 52);
INSERT INTO role_permissions (role_id, permission_id) VALUES (5, 53);
INSERT INTO role_permissions (role_id, permission_id) VALUES (5, 54);
INSERT INTO role_permissions (role_id, permission_id) VALUES (5, 55);
INSERT INTO role_permissions (role_id, permission_id) VALUES (5, 56);
INSERT INTO role_permissions (role_id, permission_id) VALUES (5, 57);
INSERT INTO role_permissions (role_id, permission_id) VALUES (5, 58);
INSERT INTO role_permissions (role_id, permission_id) VALUES (5, 59);
INSERT INTO role_permissions (role_id, permission_id) VALUES (5, 60);
INSERT INTO role_permissions (role_id, permission_id) VALUES (5, 61);
INSERT INTO role_permissions (role_id, permission_id) VALUES (5, 62);
INSERT INTO role_permissions (role_id, permission_id) VALUES (5, 63);
INSERT INTO role_permissions (role_id, permission_id) VALUES (6, 1);
INSERT INTO role_permissions (role_id, permission_id) VALUES (6, 2);
INSERT INTO role_permissions (role_id, permission_id) VALUES (6, 6);
INSERT INTO role_permissions (role_id, permission_id) VALUES (6, 19);
INSERT INTO role_permissions (role_id, permission_id) VALUES (6, 27);
INSERT INTO role_permissions (role_id, permission_id) VALUES (6, 33);
INSERT INTO role_permissions (role_id, permission_id) VALUES (6, 41);
INSERT INTO role_permissions (role_id, permission_id) VALUES (6, 47);
INSERT INTO role_permissions (role_id, permission_id) VALUES (6, 48);
INSERT INTO role_permissions (role_id, permission_id) VALUES (6, 64);
INSERT INTO role_permissions (role_id, permission_id) VALUES (6, 65);
INSERT INTO role_permissions (role_id, permission_id) VALUES (6, 66);
INSERT INTO role_permissions (role_id, permission_id) VALUES (6, 67);
INSERT INTO role_permissions (role_id, permission_id) VALUES (6, 68);
INSERT INTO role_permissions (role_id, permission_id) VALUES (6, 69);
INSERT INTO role_permissions (role_id, permission_id) VALUES (6, 70);
INSERT INTO role_permissions (role_id, permission_id) VALUES (7, 1);
INSERT INTO role_permissions (role_id, permission_id) VALUES (7, 2);
INSERT INTO role_permissions (role_id, permission_id) VALUES (7, 6);
INSERT INTO role_permissions (role_id, permission_id) VALUES (7, 10);
INSERT INTO role_permissions (role_id, permission_id) VALUES (7, 15);
INSERT INTO role_permissions (role_id, permission_id) VALUES (7, 19);
INSERT INTO role_permissions (role_id, permission_id) VALUES (7, 28);
INSERT INTO role_permissions (role_id, permission_id) VALUES (7, 33);
INSERT INTO role_permissions (role_id, permission_id) VALUES (7, 42);
INSERT INTO role_permissions (role_id, permission_id) VALUES (7, 47);
INSERT INTO role_permissions (role_id, permission_id) VALUES (7, 49);
INSERT INTO role_permissions (role_id, permission_id) VALUES (7, 53);
INSERT INTO role_permissions (role_id, permission_id) VALUES (7, 57);
INSERT INTO role_permissions (role_id, permission_id) VALUES (7, 61);
INSERT INTO role_permissions (role_id, permission_id) VALUES (7, 64);
INSERT INTO role_permissions (role_id, permission_id) VALUES (7, 69);

-- ---------- admin 账号 ----------
-- 只在不存在时插入，避免覆盖已改过的密码
INSERT INTO users (username, email, password_hash, full_name, phone, role_id, status, created_at, updated_at)
SELECT 'admin', 'admin@example.com', '47815102527309d1fd427450d71c0d7e:6768e1614a1098be0346163462facc3924188b2764587da9465c9a600c965fb0', '系统管理员', NULL, 1, 1, '2026-09-30 13:43:47.420243', '2026-09-30 13:43:47.420243'
WHERE NOT EXISTS (SELECT 1 FROM users WHERE username = 'admin');

-- ---------- 默认仓库 ----------
INSERT INTO warehouses (name, address, manager, phone, status, created_at)
SELECT '默认仓库', '总部', NULL, NULL, 1, '2026-09-30 13:43:47.420243'
WHERE NOT EXISTS (SELECT 1 FROM warehouses WHERE name = '默认仓库');
